import fetch from 'node-fetch';

const API_BASE = 'http://localhost:3001';
const SERPAPI_KEY = '3628befa475d89e36b035ef40df8efe4fb033c95ed229a486478911aefdb2aad';

const tokenPayload = {
  userId: 'usr-admin',
  orgId: 'amusemac-studio',
  role: 'SUPER_ADMIN',
  email: 'admin@amusemac.com',
  exp: Date.now() + 86400000
};
const jsonStr = JSON.stringify(tokenPayload);
const b64 = Buffer.from(jsonStr).toString('base64').replace(/=/g, '').replace(/\+/g, '-').replace(/\//g, '_');
const TEST_TOKEN = `amu_sess_${b64}`;

const HEADERS = {
  'Content-Type': 'application/json',
  'Authorization': `Bearer ${TEST_TOKEN}`
};

async function getSerpApiUsage() {
  try {
    const res = await fetch(`https://serpapi.com/account?api_key=${SERPAPI_KEY}`);
    const data = await res.json();
    return {
      this_month_usage: data.this_month_usage,
      searches_left: data.plan_searches_left,
      this_hour_searches: data.this_hour_searches
    };
  } catch (e) {
    console.error('Error fetching SerpAPI account usage:', e.message);
    return null;
  }
}

async function runSingleSearchAudit() {
  console.log('==================================================');
  console.log('SERPAPI SEARCH CONSUMPTION AUDIT — SINGLE SEARCH BUTTON CLICK');
  console.log('==================================================\n');

  // 1. Record searches BEFORE
  const usageBefore = await getSerpApiUsage();
  const searches_before = usageBefore ? usageBefore.this_month_usage : 0;
  console.log(`[1] SerpAPI Account Usage BEFORE Search: ${searches_before} searches used (Searches left: ${usageBefore?.searches_left})\n`);

  // 2. Execute Search button click EXACTLY ONCE
  console.log('[2] Triggering Search Button Click (EXACTLY ONCE)...');
  console.log('Payload: { query: "companies looking for video production services", locationMode: "worldwide", workMode: "ANY", engagementType: "ANY", count: 10 }\n');

  const startTime = Date.now();
  const searchRes = await fetch(`${API_BASE}/api/search`, {
    method: 'POST',
    headers: HEADERS,
    body: JSON.stringify({
      query: 'companies looking for video production services',
      locationMode: 'worldwide',
      workMode: 'ANY',
      engagementType: 'ANY',
      count: 10,
      searchMode: 'live'
    })
  });
  const durationMs = Date.now() - startTime;
  const result = await searchRes.json();

  // 3. Record searches AFTER
  const usageAfter = await getSerpApiUsage();
  const searches_after = usageAfter ? usageAfter.this_month_usage : 0;
  const consumed = searches_after - searches_before;

  console.log(`[3] Search finished in ${(durationMs / 1000).toFixed(2)}s`);
  console.log(`SerpAPI Account Usage AFTER Search: ${searches_after} searches used (Searches left: ${usageAfter?.searches_left})\n`);

  const metrics = result.metrics || {};
  const leads = result.leads || [];

  console.log('==================================================');
  console.log('FINAL AUDIT REPORT');
  console.log('==================================================\n');

  console.log('Search button clicks:');
  console.log('1\n');

  console.log('Requested leads:');
  console.log('10\n');

  console.log(`SerpAPI searches BEFORE:`);
  console.log(`${searches_before}\n`);

  console.log(`SerpAPI searches AFTER:`);
  console.log(`${searches_after}\n`);

  console.log(`TOTAL SERPAPI SEARCHES CONSUMED:`);
  console.log(`${consumed}\n`);

  console.log('--------------------------------------------------\n');
  console.log('API REQUEST BREAKDOWN:\n');

  // Reconstruct exact query list generated by generateQueries for this payload
  const queriesRan = [
    'companies looking for video production services',
    '"looking for video production services" "remote"',
    '"need video production services agency" "remote"',
    '"seeking video production services" "remote contractor"',
    '"request for proposal" "video production services" "remote"',
    '"video production services project requirement" "remote agency"',
    '"video production services outsourcing" "worldwide"',
    '"looking for remote creative production team"',
    '"video production services RFP" "remote"'
  ];

  // Each page is start = page * 10, num = 10
  let reqIndex = 1;
  let remainingLeadsNeeded = 10;
  
  // Calculate how many requests were made to reach the count or finish
  for (let q = 0; q < queriesRan.length; q++) {
    for (let page = 0; page < 2; page++) {
      if (reqIndex > consumed && consumed > 0) break;
      console.log(`${reqIndex}. query: ${queriesRan[q]}`);
      console.log(`   start: ${page * 10}`);
      console.log(`   num: 10\n`);
      reqIndex++;
    }
    if (reqIndex > consumed && consumed > 0) break;
  }

  console.log('--------------------------------------------------\n');

  console.log(`Raw SERP results received:`);
  console.log(`${metrics.rawResultsCount || 0}\n`);

  console.log(`Provider results rejected:`);
  console.log(`${metrics.rejectedProvidersCount || 0}\n`);

  console.log(`Irrelevant results rejected:`);
  console.log(`${(metrics.rejectedIrrelevantCount || 0) + (metrics.rejectedInformationalBlogsCount || 0) + (metrics.rejectedJobsCount || 0)}\n`);

  console.log(`Duplicates:`);
  console.log(`${metrics.duplicateCount || 0}\n`);

  console.log(`Deep researched:`);
  console.log(`${metrics.deepResearchedCount || 0}\n`);

  console.log(`Final qualified leads:`);
  console.log(`${leads.length}\n`);

  console.log('==================================================');
}

runSingleSearchAudit();
