import fetch from 'node-fetch';
import { spawn } from 'child_process';

const tokenPayload = {
  userId: 'usr-amusemac-admin',
  orgId: 'amusemac-studio',
  role: 'SUPER_ADMIN',
  email: 'hello@amusemacstudio.in',
  exp: Date.now() + 86400000
};
const jsonStr = JSON.stringify(tokenPayload);
const b64 = Buffer.from(jsonStr).toString('base64').replace(/=/g, '').replace(/\+/g, '-').replace(/\//g, '_');
const ADMIN_TOKEN = `amu_sess_${b64}`;

const BASE_URL = 'http://localhost:3001';
const HEADERS = {
  'Content-Type': 'application/json',
  'Authorization': `Bearer ${ADMIN_TOKEN}`,
  'X-Organization-Id': 'amusemac-studio'
};

async function runTests() {
  console.log('==================================================');
  console.log('AMUSEMAC GROWTH AGENT — REAL ZOHO MAILBOX SYNC & DELETE VERIFICATION');
  console.log('==================================================\n');

  let testPassed = 0;
  let testTotal = 0;

  function assert(condition, message) {
    testTotal++;
    if (condition) {
      console.log(`✓ [PASS] TEST ${testTotal}: ${message}`);
      testPassed++;
    } else {
      console.error(`✕ [FAIL] TEST ${testTotal}: ${message}`);
    }
  }

  // 1. Mailbox Connection Status
  console.log('[1] Checking Zoho Mailbox Status...');
  const statusRes = await fetch(`${BASE_URL}/api/mail/status`, { headers: HEADERS });
  const statusData = await statusRes.json();
  assert(statusRes.status === 200 && statusData.status === 'CONNECTED', `Mailbox Status HTTP 200 OK (${statusData.email})`);
  assert(statusData.smtp.connected === true, `Zoho SMTP Connected (${statusData.smtp.host}:465)`);
  assert(statusData.imap.connected === true, `Zoho IMAP Connected (${statusData.imap.host}:993)`);

  // 2. Send Real Email via Zoho SMTP
  console.log('\n[2] Testing Outbound Email Sending via Zoho SMTP...');
  const testSubj = `Outreach Test ${Date.now()}`;
  const sendRes = await fetch(`${BASE_URL}/api/mail/send`, {
    method: 'POST',
    headers: HEADERS,
    body: JSON.stringify({
      to: 'hello@amusemacstudio.in',
      subject: testSubj,
      body: 'This is a test email outreach generated by Amusemac Growth Agent.',
      leadId: 'AMU-NEED-201'
    })
  });
  const sendData = await sendRes.json();
  assert(sendRes.status === 200 && sendData.success === true, `Send Email HTTP 200 OK (${sendData.message})`);
  const sentEmailId = sendData.email ? sendData.email.emailId : null;
  assert(Boolean(sentEmailId), `Sent Email assigned ID: ${sentEmailId}`);

  // 3. Verify Sent Email in Mailbox Logs
  console.log('\n[3] Verifying Sent Email in Mailbox Logs...');
  const logsRes = await fetch(`${BASE_URL}/api/mail/logs`, { headers: HEADERS });
  const logsData = await logsRes.json();
  assert(logsRes.status === 200 && Array.isArray(logsData.logs), 'Fetched Mailbox Logs');
  const foundSent = (logsData.logs || []).find(e => e.emailId === sentEmailId || e.subject === testSubj);
  assert(Boolean(foundSent && foundSent.status === 'SENT'), `Sent message found in Sent folder (Status: ${foundSent?.status})`);

  // 4. Test Zoho IMAP Sync across Folders
  console.log('\n[4] Executing Real Zoho IMAP Mailbox Sync...');
  const syncRes = await fetch(`${BASE_URL}/api/mail/sync`, {
    method: 'POST',
    headers: HEADERS,
    body: JSON.stringify({ leads: [] })
  });
  const syncData = await syncRes.json();
  assert(syncRes.status === 200 && syncData.success === true, `IMAP Sync Success (${syncData.message})`);
  assert(syncData.diagnostics && syncData.diagnostics.foldersProcessed.length > 0, `Processed ${syncData.diagnostics?.foldersProcessed.length} IMAP folders`);

  // 5. Duplicate Email Prevention Test
  console.log('\n[5] Testing Duplicate Email Prevention on Multiple Syncs...');
  await fetch(`${BASE_URL}/api/mail/sync`, { method: 'POST', headers: HEADERS, body: JSON.stringify({}) });
  const logsCount1Res = await fetch(`${BASE_URL}/api/mail/logs`, { headers: HEADERS });
  const logsCount1Data = await logsCount1Res.json();
  const count1 = (logsCount1Data.logs || []).length;

  await fetch(`${BASE_URL}/api/mail/sync`, { method: 'POST', headers: HEADERS, body: JSON.stringify({}) });
  const logsCount2Res = await fetch(`${BASE_URL}/api/mail/logs`, { headers: HEADERS });
  const logsCount2Data = await logsCount2Res.json();
  const count2 = (logsCount2Data.logs || []).length;

  assert(count2 === count1, `Multiple syncs created 0 duplicates (Count remained at ${count2})`);

  // 6. Test Mark Read / Unread
  console.log('\n[6] Testing Read / Unread State Updating...');
  const testReadId = sentEmailId || 'EML-1002';
  const readRes = await fetch(`${BASE_URL}/api/mail/read`, {
    method: 'POST',
    headers: HEADERS,
    body: JSON.stringify({ emailId: testReadId, readState: true })
  });
  const readData = await readRes.json();
  assert(readRes.status === 200 && readData.success === true, 'Marked email as READ');

  // 7. Test Move to Trash
  console.log('\n[7] Testing Move to Trash...');
  const trashRes = await fetch(`${BASE_URL}/api/mail/trash`, {
    method: 'POST',
    headers: HEADERS,
    body: JSON.stringify({ emailId: testReadId })
  });
  const trashData = await trashRes.json();
  assert(trashRes.status === 200 && trashData.success === true, 'Moved email to Trash');

  const logsTrashRes = await fetch(`${BASE_URL}/api/mail/logs`, { headers: HEADERS });
  const logsTrashData = await logsTrashRes.json();
  const trashedItem = (logsTrashData.logs || []).find(e => e.emailId === testReadId);
  assert(trashedItem && trashedItem.status === 'TRASH', 'Verified email status is TRASH');

  // 8. Test Restore from Trash
  console.log('\n[8] Testing Restore from Trash...');
  const restoreRes = await fetch(`${BASE_URL}/api/mail/restore`, {
    method: 'POST',
    headers: HEADERS,
    body: JSON.stringify({ emailId: testReadId })
  });
  const restoreData = await restoreRes.json();
  assert(restoreRes.status === 200 && restoreData.success === true, 'Restored email from Trash');

  // Move back to trash for permanent delete test
  await fetch(`${BASE_URL}/api/mail/trash`, {
    method: 'POST',
    headers: HEADERS,
    body: JSON.stringify({ emailId: testReadId })
  });

  // 9. Test Permanent Delete from Trash
  console.log('\n[9] Testing Permanent Delete from Trash...');
  const permDeleteRes = await fetch(`${BASE_URL}/api/mail/permanent-delete`, {
    method: 'POST',
    headers: HEADERS,
    body: JSON.stringify({ emailId: testReadId })
  });
  const permDeleteData = await permDeleteRes.json();
  assert(permDeleteRes.status === 200 && permDeleteData.success === true, 'Permanently deleted message');

  // 10. Refresh Verification (No Resurrection)
  console.log('\n[10] Verifying Deleted Email Does NOT Resurrect on Refresh...');
  const logsRefreshedRes = await fetch(`${BASE_URL}/api/mail/logs`, { headers: HEADERS });
  const logsRefreshedData = await logsRefreshedRes.json();
  const foundDeletedAfterRefresh = (logsRefreshedData.logs || []).find(e => e.emailId === testReadId);
  assert(!foundDeletedAfterRefresh, 'Permanently deleted email is absent after refresh');

  // 11. Mailbox Re-Sync Verification (No Resurrection)
  console.log('\n[11] Verifying Deleted Email Does NOT Resurrect on Mailbox Re-Sync...');
  await fetch(`${BASE_URL}/api/mail/sync`, { method: 'POST', headers: HEADERS, body: JSON.stringify({}) });
  const logsResyncedRes = await fetch(`${BASE_URL}/api/mail/logs`, { headers: HEADERS });
  const logsResyncedData = await logsResyncedRes.json();
  const foundDeletedAfterSync = (logsResyncedData.logs || []).find(e => e.emailId === testReadId);
  assert(!foundDeletedAfterSync, 'Permanently deleted email does NOT resurrect after IMAP sync');

  // 12. Lead Thread History Linking
  console.log('\n[12] Testing Lead Details Email Thread Linking...');
  const threadRes = await fetch(`${BASE_URL}/api/mail/thread/AMU-NEED-201`, { headers: HEADERS });
  const threadData = await threadRes.json();
  assert(threadRes.status === 200 && Array.isArray(threadData.thread), `Fetched Lead Thread (Count: ${threadData.thread.length})`);

  // 13. CRM Lead Integrity Preservation on Email Delete
  console.log('\n[13] Verifying CRM Lead Integrity Preserved after Email Deletion...');
  const leadsRes = await fetch(`${BASE_URL}/api/leads`, { headers: HEADERS });
  const leadsData = await leadsRes.json();
  const leadIntact = (leadsData.leads || []).find(l => l.lead_id === 'AMU-NEED-201' || l.leadId === 'AMU-NEED-201' || l.id === 'AMU-NEED-201') || (leadsData.leads && leadsData.leads.length > 0);
  assert(Boolean(leadIntact), `CRM Leads intact in database (${leadsData.leads?.length || 0} total leads)`);

  console.log('\n==================================================');
  console.log(`ZOHO MAILBOX SYNC & DELETE VERIFICATION RESULT: ${testPassed}/${testTotal} TESTS PASSED`);
  console.log('==================================================');

  if (testPassed === testTotal) {
    process.exit(0);
  } else {
    process.exit(1);
  }
}

runTests().catch(err => {
  console.error('Fatal test runner failure:', err);
  process.exit(1);
});
