const B2B_COMPANY_CATALOG = [
  // 1. Film & Media Production (Mumbai / Delhi)
  {
    leadId: 'AMU-B2B-101',
    companyName: 'Red Chillies VFX & Post',
    website: 'https://www.redchilliesvfx.com',
    industry: 'Film & Media Production',
    location: 'Mumbai',
    country: 'India',
    companySize: '201-500',
    businessDescription: 'Premier visual effects and post-production studio specializing in feature films, OTT series, and high-end commercial VFX.',
    servicesProvided: ['Visual Effects', 'Post Production', '3D Animation', 'Color Grading'],
    keywords: ['vfx', 'visual effects', 'post production', 'film production', 'animation', 'cgi', 'mumbai', 'production house'],
    projectName: 'Feature Film Visual Effects & Line Production',
    serviceNeed: 'Visual Effects & Post Production Line Partner',
    primaryService: 'Post Production',
    buyingSignal: 'Expanding VFX studio capacity for 3 tentpole feature films in 2026.',
    buyingSignalType: 'PRODUCTION_HIRING',
    estimatedProjectValue: '₹40L – ₹1Cr',
    aiScore: 94,
    scoreTier: 'HOT',
    confidenceScore: 92,
    decisionMakerName: 'Keitan Yadav',
    decisionMakerDesignation: 'Chief Operating Officer & VFX Producer',
    email: 'contact@redchilliesvfx.com',
    phone: '+91 22 6171 7777',
    outreachStatus: 'DISCOVERED',
    competitorCheckStatus: 'CLIENT_END_USER',
    verificationStatus: 'LOCAL_DATASET',
    researchDate: '2026-08-15',
    priority: 'HOT',
    scoreReason: 'Top tier film production & VFX studio with active tentpole project expansion.',
    whyThisLead: 'Leading Mumbai VFX studio seeking specialized production line and post-production partners.',
    sourceUrls: ['https://www.redchilliesvfx.com']
  },
  {
    leadId: 'AMU-B2B-102',
    companyName: 'Chrome Pictures',
    website: 'https://www.chromepictures.com',
    industry: 'Film & Media Production',
    location: 'Mumbai',
    country: 'India',
    companySize: '51-200',
    businessDescription: 'Award-winning ad film production house behind top national brand campaigns, TVCs, and narrative cinema.',
    servicesProvided: ['Ad Film Production', 'TVC Direction', 'Brand Films', 'Line Production'],
    keywords: ['production house', 'ad films', 'tvc', 'commercials', 'brand films', 'mumbai', 'film production'],
    projectName: 'Q4 National TVC Campaign Line Production',
    serviceNeed: 'Turnkey Line Production & Location Scouting',
    primaryService: 'Commercial/Ad Film Production',
    buyingSignal: 'Issued vendor call for line production partners for upcoming Q4 FMCG campaign.',
    buyingSignalType: 'RFP_VENDOR_CALL',
    estimatedProjectValue: '₹25L – ₹60L',
    aiScore: 91,
    scoreTier: 'HOT',
    confidenceScore: 90,
    decisionMakerName: 'Amit Sharma',
    decisionMakerDesignation: 'Director & Co-Founder',
    email: 'info@chromepictures.com',
    phone: '+91 22 2630 1414',
    outreachStatus: 'DISCOVERED',
    competitorCheckStatus: 'CLIENT_END_USER',
    verificationStatus: 'LOCAL_DATASET',
    researchDate: '2026-08-15',
    priority: 'HOT',
    scoreReason: 'Active TVC production schedule requiring fast-turnaround line teams.',
    whyThisLead: 'High-volume commercial production studio with recurring line production budgets.',
    sourceUrls: ['https://www.chromepictures.com']
  },
  {
    leadId: 'AMU-B2B-103',
    companyName: 'Excel Entertainment',
    website: 'https://www.excelentertainment.com',
    industry: 'Film & Media Production',
    location: 'Mumbai',
    country: 'India',
    companySize: '201-500',
    businessDescription: 'Pioneering Indian film and OTT streaming series production house producing critically acclaimed cinema.',
    servicesProvided: ['Feature Films', 'OTT Series Production', 'Creative Development', 'Film Executive Production'],
    keywords: ['film production', 'production house', 'ott series', 'cinema', 'feature films', 'mumbai', 'entertainment'],
    projectName: 'New OTT Original Series Production',
    serviceNeed: 'Soundstage & Set Engineering Partner',
    primaryService: 'Film Production',
    buyingSignal: 'Announced 4 new OTT original series greenlit for production.',
    buyingSignalType: 'NEW_PRODUCT_LAUNCH',
    estimatedProjectValue: '₹50L – ₹1.5Cr',
    aiScore: 95,
    scoreTier: 'HOT',
    confidenceScore: 94,
    decisionMakerName: 'Ritesh Sidhwani',
    decisionMakerDesignation: 'Producer & Co-Founder',
    email: 'business@excelentertainment.com',
    phone: '+91 22 2673 2222',
    outreachStatus: 'DISCOVERED',
    competitorCheckStatus: 'CLIENT_END_USER',
    verificationStatus: 'LOCAL_DATASET',
    researchDate: '2026-08-15',
    priority: 'HOT',
    scoreReason: 'Greenlit streaming series lineup with large physical production scale.',
    whyThisLead: 'Tier-1 production house actively filming multi-episode web series.',
    sourceUrls: ['https://www.excelentertainment.com']
  },
  {
    leadId: 'AMU-B2B-104',
    companyName: 'Phantom Studios',
    website: 'https://www.phantomstudios.in',
    industry: 'Film & Media Production',
    location: 'Mumbai',
    country: 'India',
    companySize: '51-200',
    businessDescription: 'Dynamic film production studio focusing on groundbreaking storytelling, feature films, and digital content.',
    servicesProvided: ['Feature Film Production', 'Digital Content', 'Script Development', 'Post Production'],
    keywords: ['phantom', 'film production', 'production house', 'cinema', 'digital content', 'mumbai', 'media'],
    projectName: 'Indie Feature Film Co-Production',
    serviceNeed: 'Line Production & Technical Equipment',
    primaryService: 'Film Production',
    buyingSignal: 'Secured co-production deal for 2 independent feature films.',
    buyingSignalType: 'NEW_PARTNERSHIP',
    estimatedProjectValue: '₹20L – ₹45L',
    aiScore: 88,
    scoreTier: 'WARM',
    confidenceScore: 86,
    decisionMakerName: 'Srishti Behl',
    decisionMakerDesignation: 'CEO',
    email: 'contact@phantomstudios.in',
    phone: '+91 22 2639 9900',
    outreachStatus: 'DISCOVERED',
    competitorCheckStatus: 'CLIENT_END_USER',
    verificationStatus: 'LOCAL_DATASET',
    researchDate: '2026-08-15',
    priority: 'WARM',
    scoreReason: 'Independent cinema co-production requiring agile line execution.',
    whyThisLead: 'Active studio producing feature content for theatrical and streaming platforms.',
    sourceUrls: ['https://www.phantomstudios.in']
  },

  // 2. AI & Software Startups (Bangalore / Hyderabad / Pune)
  {
    leadId: 'AMU-B2B-201',
    companyName: 'Hasura Technologies',
    website: 'https://hasura.io',
    industry: 'Software & AI',
    location: 'Bangalore',
    country: 'India',
    companySize: '51-200',
    businessDescription: 'Global developer data platform providing instant GraphQL & REST APIs over databases with real-time security.',
    servicesProvided: ['GraphQL Engine', 'Database APIs', 'Developer Tools', 'Data Federation'],
    keywords: ['hasura', 'graphql', 'developer tools', 'saas', 'software', 'ai', 'bangalore', 'api', 'it company'],
    projectName: 'Developer Experience Explainer & Launch Video',
    serviceNeed: 'High-Tech Motion Graphics & Product Video Production',
    primaryService: 'Product Video Production',
    buyingSignal: 'Launched Hasura Data Delivery Engine with developer marketing push.',
    buyingSignalType: 'NEW_PRODUCT_LAUNCH',
    estimatedProjectValue: '₹15L – ₹35L',
    aiScore: 92,
    scoreTier: 'HOT',
    confidenceScore: 90,
    decisionMakerName: 'Tanmai Gopal',
    decisionMakerDesignation: 'CEO & Co-Founder',
    email: 'hello@hasura.io',
    phone: '+91 80 4123 9988',
    outreachStatus: 'DISCOVERED',
    competitorCheckStatus: 'CLIENT_END_USER',
    verificationStatus: 'LOCAL_DATASET',
    researchDate: '2026-08-15',
    priority: 'HOT',
    scoreReason: 'Series B developer tool startup actively scaling global product marketing.',
    whyThisLead: 'High-growth Bangalore tech startup needing technical product motion graphics.',
    sourceUrls: ['https://hasura.io']
  },
  {
    leadId: 'AMU-B2B-202',
    companyName: 'Yellow.ai',
    website: 'https://yellow.ai',
    industry: 'Software & AI',
    location: 'Bangalore',
    country: 'India',
    companySize: '201-500',
    businessDescription: 'Enterprise conversational AI platform automating customer experience across voice and chat channels.',
    servicesProvided: ['Conversational AI', 'Generative AI Support', 'Omnichannel Automation', 'Voice Bots'],
    keywords: ['yellow ai', 'conversational ai', 'artificial intelligence', 'saas', 'bangalore', 'chatbots', 'it company', 'ai company'],
    projectName: 'Global Enterprise AI Summit Video Campaign',
    serviceNeed: 'Enterprise Brand Film & Case Study Video Shoot',
    primaryService: 'Brand Film Production',
    buyingSignal: 'Announced Series C expansion and European market entry.',
    buyingSignalType: 'EXPANSION_SIGNAL',
    estimatedProjectValue: '₹30L – ₹75L',
    aiScore: 93,
    scoreTier: 'HOT',
    confidenceScore: 91,
    decisionMakerName: 'Raghu Ravinutala',
    decisionMakerDesignation: 'CEO & Co-Founder',
    email: 'contact@yellow.ai',
    phone: '+91 80 6789 1234',
    outreachStatus: 'DISCOVERED',
    competitorCheckStatus: 'CLIENT_END_USER',
    verificationStatus: 'LOCAL_DATASET',
    researchDate: '2026-08-15',
    priority: 'HOT',
    scoreReason: 'Global enterprise AI platform expanding international brand presence.',
    whyThisLead: 'Well-funded AI unicorn with dedicated enterprise video production budgets.',
    sourceUrls: ['https://yellow.ai']
  },
  {
    leadId: 'AMU-B2B-203',
    companyName: 'Darwinbox HR Tech',
    website: 'https://darwinbox.com',
    industry: 'Software & AI',
    location: 'Hyderabad',
    country: 'India',
    companySize: '500+',
    businessDescription: 'Unicorn HCM cloud platform transforming Human Capital Management for enterprises across Asia and MENA.',
    servicesProvided: ['HR Tech SaaS', 'Enterprise HCM', 'Employee Engagement', 'Payroll Automation'],
    keywords: ['darwinbox', 'hr tech', 'saas', 'hcm', 'hyderabad', 'enterprise software', 'it company'],
    projectName: 'MENA Expansion Brand Campaign Film',
    serviceNeed: 'Corporate Brand Film & Multi-Language Video Production',
    primaryService: 'Corporate Video Production',
    buyingSignal: 'Expanded operations to Middle East & Southeast Asia with $72M funding.',
    buyingSignalType: 'FUNDING_RAISED',
    estimatedProjectValue: '₹35L – ₹80L',
    aiScore: 95,
    scoreTier: 'HOT',
    confidenceScore: 93,
    decisionMakerName: 'Chaitanya Peddi',
    decisionMakerDesignation: 'Co-Founder & Product Head',
    email: 'info@darwinbox.com',
    phone: '+91 40 4567 8900',
    outreachStatus: 'DISCOVERED',
    competitorCheckStatus: 'CLIENT_END_USER',
    verificationStatus: 'LOCAL_DATASET',
    researchDate: '2026-08-15',
    priority: 'HOT',
    scoreReason: 'SaaS unicorn expanding globally with strong demand for international corporate video.',
    whyThisLead: 'Hyderabad-based enterprise SaaS giant scaling global customer success media.',
    sourceUrls: ['https://darwinbox.com']
  },
  {
    leadId: 'AMU-B2B-204',
    companyName: 'Mindtickle',
    website: 'https://www.mindtickle.com',
    industry: 'Software & AI',
    location: 'Pune',
    country: 'India',
    companySize: '201-500',
    businessDescription: 'Sales readiness and revenue enablement platform helping Fortune 500 sales teams increase revenue productivity.',
    servicesProvided: ['Sales Readiness SaaS', 'Revenue Enablement', 'Sales Coaching', 'AI Analytics'],
    keywords: ['mindtickle', 'sales tech', 'pune', 'saas', 'software', 'revenue enablement', 'it company'],
    projectName: 'Annual Customer Conference Media Production',
    serviceNeed: 'Keynote Coverage & Customer Testimonial Video Production',
    primaryService: 'Event & Testimonial Video Production',
    buyingSignal: 'Hosting annual global revenue enablement conference in Pune & US.',
    buyingSignalType: 'UPCOMING_EVENT',
    estimatedProjectValue: '₹20L – ₹40L',
    aiScore: 89,
    scoreTier: 'WARM',
    confidenceScore: 88,
    decisionMakerName: 'Krishna Depura',
    decisionMakerDesignation: 'CEO & Co-Founder',
    email: 'contact@mindtickle.com',
    phone: '+91 20 6712 3456',
    outreachStatus: 'DISCOVERED',
    competitorCheckStatus: 'CLIENT_END_USER',
    verificationStatus: 'LOCAL_DATASET',
    researchDate: '2026-08-15',
    priority: 'WARM',
    scoreReason: 'Upcoming global summit requiring professional media production coverage.',
    whyThisLead: 'Pune-based SaaS unicorn with ongoing need for customer video testimonials.',
    sourceUrls: ['https://www.mindtickle.com']
  },

  // 3. Advertising & Creative Agencies (Delhi NCR / Mumbai / Bangalore)
  {
    leadId: 'AMU-B2B-301',
    companyName: 'Schbang Digital & Creative',
    website: 'https://www.schbang.com',
    industry: 'Advertising & Marketing',
    location: 'Mumbai',
    country: 'India',
    companySize: '201-500',
    businessDescription: 'Integrated creative, digital media, and technology agency delivering end-to-end brand experiences for top Indian conglomerates.',
    servicesProvided: ['Integrated Marketing', 'Creative Strategy', 'Digital Advertising', 'Media Production'],
    keywords: ['schbang', 'advertising agency', 'ad agency', 'digital agency', 'creative', 'marketing', 'mumbai'],
    projectName: 'Festive Season Ad Shoot Line Support',
    serviceNeed: 'Commercial Line Production & Studio Hire',
    primaryService: 'Commercial/Ad Film Production',
    buyingSignal: 'Won digital & creative mandate for 5 major festive brand accounts.',
    buyingSignalType: 'RFP_VENDOR_CALL',
    estimatedProjectValue: '₹40L – ₹90L',
    aiScore: 96,
    scoreTier: 'HOT',
    confidenceScore: 94,
    decisionMakerName: 'Harshil Karia',
    decisionMakerDesignation: 'Founder & MD',
    email: 'info@schbang.com',
    phone: '+91 22 6123 4567',
    outreachStatus: 'DISCOVERED',
    competitorCheckStatus: 'CLIENT_END_USER',
    verificationStatus: 'LOCAL_DATASET',
    researchDate: '2026-08-15',
    priority: 'HOT',
    scoreReason: 'Multi-account mandate win creating immediate production line demand.',
    whyThisLead: 'Top Indian creative agency frequently outsourcing line production and post-production.',
    sourceUrls: ['https://www.schbang.com']
  },
  {
    leadId: 'AMU-B2B-302',
    companyName: 'Dentsu Webchutney',
    website: 'https://webchutney.com',
    industry: 'Advertising & Marketing',
    location: 'Bangalore',
    country: 'India',
    companySize: '201-500',
    businessDescription: 'Globally recognized creative technology and digital advertising agency celebrated for Cannes Lion winning campaigns.',
    servicesProvided: ['Digital Campaigns', 'Creative Tech', 'Social Strategy', 'Video Content'],
    keywords: ['webchutney', 'dentsu', 'advertising agency', 'ad agency', 'creative', 'bangalore', 'digital marketing'],
    projectName: 'Tech Brand Interactive Digital Film',
    serviceNeed: 'CGI & Interactive Video Production Partner',
    primaryService: 'Interactive Video Production',
    buyingSignal: 'Piloting interactive AI brand campaign for consumer tech client.',
    buyingSignalType: 'CAMPAIGN_ANNOUNCEMENT',
    estimatedProjectValue: '₹25L – ₹50L',
    aiScore: 93,
    scoreTier: 'HOT',
    confidenceScore: 91,
    decisionMakerName: 'Gurbaksh Singh',
    decisionMakerDesignation: 'Chief Innovation Officer',
    email: 'contact@webchutney.com',
    phone: '+91 80 4321 8765',
    outreachStatus: 'DISCOVERED',
    competitorCheckStatus: 'CLIENT_END_USER',
    verificationStatus: 'LOCAL_DATASET',
    researchDate: '2026-08-15',
    priority: 'HOT',
    scoreReason: 'Cannes Lion winning agency driving innovative tech-enabled brand films.',
    whyThisLead: 'Bangalore creative tech powerhouse seeking specialized video innovation partners.',
    sourceUrls: ['https://webchutney.com']
  },
  {
    leadId: 'AMU-B2B-303',
    companyName: 'FCB Ulka Advertising',
    website: 'https://www.fcbulka.com',
    industry: 'Advertising & Marketing',
    location: 'Delhi',
    country: 'India',
    companySize: '201-500',
    businessDescription: 'Legacy full-service advertising agency network crafting iconic brand strategies and national television campaigns.',
    servicesProvided: ['Brand Strategy', 'Television Advertising', 'Print & Outdoor', 'Media Buying'],
    keywords: ['fcb ulka', 'advertising agency', 'ad agency', 'delhi', 'ncr', 'tvc', 'marketing'],
    projectName: 'Automobile Brand TVC Launch Shoot',
    serviceNeed: 'High-End Car Commercial Line Production & Rigging',
    primaryService: 'Commercial/Ad Film Production',
    buyingSignal: 'Awarded national launch account for flagship SUV model.',
    buyingSignalType: 'RFP_VENDOR_CALL',
    estimatedProjectValue: '₹50L – ₹1.2Cr',
    aiScore: 97,
    scoreTier: 'HOT',
    confidenceScore: 95,
    decisionMakerName: 'Kulvinder Ahluwalia',
    decisionMakerDesignation: 'President - Delhi & North',
    email: 'delhi@fcbulka.com',
    phone: '+91 11 4567 1100',
    outreachStatus: 'DISCOVERED',
    competitorCheckStatus: 'CLIENT_END_USER',
    verificationStatus: 'LOCAL_DATASET',
    researchDate: '2026-08-15',
    priority: 'HOT',
    scoreReason: 'Major SUV launch campaign requiring specialized vehicle tracking shoots.',
    whyThisLead: 'Tier-1 Delhi agency executing high-budget national television ad shoots.',
    sourceUrls: ['https://www.fcbulka.com']
  },
  {
    leadId: 'AMU-B2B-304',
    companyName: 'Social Panga',
    website: 'https://socialpanga.com',
    industry: 'Advertising & Marketing',
    location: 'Bangalore',
    country: 'India',
    companySize: '51-200',
    businessDescription: 'Fast-growing digital marketing and creative production studio building high-engagement video content for D2C brands.',
    servicesProvided: ['Social Media Marketing', 'D2C Video Content', 'Influencer Campaigns', 'Branding'],
    keywords: ['social panga', 'digital agency', 'advertising agency', 'social media', 'bangalore', 'd2c marketing'],
    projectName: 'D2C Brands Reel & Short Form Video Package',
    serviceNeed: 'Short Form Video Production & Studio Space',
    primaryService: 'Content Production',
    buyingSignal: 'Opened new production wing in Bangalore & Delhi.',
    buyingSignalType: 'NEW_LOCATION_EXPANSION',
    estimatedProjectValue: '₹12L – ₹28L',
    aiScore: 87,
    scoreTier: 'WARM',
    confidenceScore: 85,
    decisionMakerName: 'Gaurav Arora',
    decisionMakerDesignation: 'Co-Founder',
    email: 'hello@socialpanga.com',
    phone: '+91 80 4956 7890',
    outreachStatus: 'DISCOVERED',
    competitorCheckStatus: 'CLIENT_END_USER',
    verificationStatus: 'LOCAL_DATASET',
    researchDate: '2026-08-15',
    priority: 'WARM',
    scoreReason: 'Expanding content wing with high monthly volume of short-form video shoots.',
    whyThisLead: 'Bangalore agency producing ongoing video content for digital D2C clients.',
    sourceUrls: ['https://socialpanga.com']
  },

  // 4. E-Commerce & Retail Tech (Gurgaon / Delhi / Bangalore / Mumbai)
  {
    leadId: 'AMU-B2B-401',
    companyName: 'Lenskart Technologies',
    website: 'https://www.lenskart.com',
    industry: 'E-Commerce & Retail',
    location: 'Delhi',
    country: 'India',
    companySize: '500+',
    businessDescription: 'Omnichannel eyewear retailer and technology pioneer redefining optical retail with AI and automated manufacturing.',
    servicesProvided: ['Eyewear E-Commerce', 'Omnichannel Retail', 'AR Try-On Tech', 'D2C Eyewear'],
    keywords: ['lenskart', 'e-commerce', 'retail tech', 'd2c', 'delhi', 'gurgaon', 'eyewear'],
    projectName: 'International Fashion Eyewear Commercial Shoot',
    serviceNeed: 'Celebrity Campaign Line Production & Studio Rental',
    primaryService: 'Commercial/Ad Film Production',
    buyingSignal: 'Signed global celebrity brand ambassador for new luxury collection.',
    buyingSignalType: 'CAMPAIGN_ANNOUNCEMENT',
    estimatedProjectValue: '₹45L – ₹95L',
    aiScore: 96,
    scoreTier: 'HOT',
    confidenceScore: 94,
    decisionMakerName: 'Peyush Bansal',
    decisionMakerDesignation: 'CEO & Co-Founder',
    email: 'marketing@lenskart.com',
    phone: '+91 124 411 2233',
    outreachStatus: 'DISCOVERED',
    competitorCheckStatus: 'CLIENT_END_USER',
    verificationStatus: 'LOCAL_DATASET',
    researchDate: '2026-08-15',
    priority: 'HOT',
    scoreReason: 'Celebrity endorsement campaign requiring top-tier commercial production design.',
    whyThisLead: 'Major Gurgaon D2C unicorn with massive quarterly advertising budgets.',
    sourceUrls: ['https://www.lenskart.com']
  },

  // 5. Fintech & Financial Services (Mumbai / Bangalore)
  {
    leadId: 'AMU-B2B-501',
    companyName: 'CRED Technologies',
    website: 'https://cred.club',
    industry: 'Fintech',
    location: 'Bangalore',
    country: 'India',
    companySize: '500+',
    businessDescription: 'High-trust fintech platform rewarding creditworthy individuals with exclusive lifestyle perks and financial products.',
    servicesProvided: ['Credit Card Payments', 'Fintech Platform', 'P2P Lending', 'Wealth Management'],
    keywords: ['cred', 'fintech', 'bangalore', 'credit cards', 'financial services', 'rewards'],
    projectName: 'IPL Season Viral Commercial Production',
    serviceNeed: 'High-Concept TVC Line Production & Celebrity Logistics',
    primaryService: 'Commercial/Ad Film Production',
    buyingSignal: 'Secured official sponsor partnership for upcoming cricket season.',
    buyingSignalType: 'SEASONAL_FESTIVE_CAMPAIGN',
    estimatedProjectValue: '₹60L – ₹1.5Cr',
    aiScore: 98,
    scoreTier: 'HOT',
    confidenceScore: 96,
    decisionMakerName: 'Kunal Shah',
    decisionMakerDesignation: 'Founder & CEO',
    email: 'press@cred.club',
    phone: '+91 80 4567 0000',
    outreachStatus: 'DISCOVERED',
    competitorCheckStatus: 'CLIENT_END_USER',
    verificationStatus: 'LOCAL_DATASET',
    researchDate: '2026-08-15',
    priority: 'HOT',
    scoreReason: 'Renowned for viral high-budget TVCs featuring sports & cinema icons.',
    whyThisLead: 'Bangalore fintech unicorn executing the highest profile ad films in India.',
    sourceUrls: ['https://cred.club']
  }
];

module.exports = { B2B_COMPANY_CATALOG };
