const BUYER_OPPORTUNITY_CATALOG = [
  // 1. Film & Media Production Buyers (Mumbai / Delhi)
  {
    id: 'AMU-OPP-101',
    leadId: 'AMU-OPP-101',
    title: 'Looking for Production Designer for Tentpole Feature Film',
    companyName: 'Surya Cinema Productions',
    requester: 'Surya Cinema Productions',
    requirement: 'Seeking an experienced Production Designer & Art Direction team for a period drama feature film shooting in Mumbai and Rajasthan.',
    matchedServices: ['Production Design', 'Art Direction', 'Film Production', 'Pre-Production'],
    serviceMatchScore: 95,
    source: 'LinkedIn Jobs',
    sourceUrl: 'https://www.linkedin.com/jobs/view/3891024101',
    location: 'Mumbai',
    country: 'India',
    postedAt: '2026-08-14',
    deadline: '2026-09-15',
    budget: '₹25L – ₹50L',
    employmentType: 'Project / Contract',
    projectType: 'Feature Film Production',
    intentType: 'HOT',
    intentScore: 96,
    matchScore: 95,
    industry: 'Film & Media Production',
    whyThisIsAMatch: 'Explicit buyer requirement for film production design and art direction team in Mumbai.',
    contactInfo: { name: 'Rajesh Nair', designation: 'Executive Producer', email: 'proposals@suryacinema.in', phone: '+91 22 2634 1122' },
    description: 'Surya Cinema is greenlighting a major period feature film. We require a turnkey Production Design team responsible for set engineering, prop sourcing, and period art direction.',
    keywords: ['production designer', 'art direction', 'film production', 'mumbai', 'feature film', 'set design'],
    status: 'DISCOVERED',
    dataStatus: 'DEMO_LOCAL',
    website: 'https://suryacinema.in',
    email: 'proposals@suryacinema.in',
    phone: '+91 22 2634 1122',
    outreachStatus: 'DISCOVERED',
    aiScore: 96,
    scoreTier: 'HOT'
  },
  {
    id: 'AMU-OPP-102',
    leadId: 'AMU-OPP-102',
    title: 'RFP: Post-Production & Sound Design Studio for OTT Web Series',
    companyName: 'Vanguard Media & Streaming',
    requester: 'Vanguard Media',
    requirement: 'Need post-production partner for 8-episode crime thriller OTT series. Requirement covers offline edit lock, color grading (DI), 5.1 Dolby sound design, and background score.',
    matchedServices: ['Post-Production', 'Sound Design', 'Film Editing', 'Background Score', 'Audio Post'],
    serviceMatchScore: 96,
    source: 'Company RFP',
    sourceUrl: 'https://vanguardmedia.in/rfp/ott-post-production-2026',
    location: 'Mumbai',
    country: 'India',
    postedAt: '2026-08-13',
    deadline: '2026-09-01',
    budget: '₹40L – ₹80L',
    employmentType: 'RFP / Tender',
    projectType: 'OTT Series Post Production',
    intentType: 'HOT',
    intentScore: 98,
    matchScore: 97,
    industry: 'Film & Media Production',
    whyThisIsAMatch: 'Active RFP for full post-production, editing, and sound design for streaming web series.',
    contactInfo: { name: 'Priya Mukherjee', designation: 'Post Production Head', email: 'post@vanguardmedia.in', phone: '+91 22 6789 4433' },
    description: 'Vanguard Media invites proposals from established post-production facilities for end-to-end post workflow of a greenlit streaming original series.',
    keywords: ['post production', 'sound design', 'background score', 'film editing', 'ott series', 'mumbai', 'rfp'],
    status: 'DISCOVERED',
    dataStatus: 'DEMO_LOCAL',
    website: 'https://vanguardmedia.in',
    email: 'post@vanguardmedia.in',
    phone: '+91 22 6789 4433',
    outreachStatus: 'DISCOVERED',
    aiScore: 98,
    scoreTier: 'HOT'
  },
  {
    id: 'AMU-OPP-103',
    leadId: 'AMU-OPP-103',
    title: 'Hiring Freelance Motion Graphics Artist for Music Video Teasers',
    companyName: 'BeatPulse Music Label',
    requester: 'BeatPulse Records',
    requirement: 'Looking for a motion designer / video editor to create 5 animated music video teasers and typography lyric videos for upcoming album release.',
    matchedServices: ['Motion Graphics', 'Music Videos', 'Reels / Shorts', 'Title Design'],
    serviceMatchScore: 92,
    source: 'Contra',
    sourceUrl: 'https://contra.com/p/beatpulse-music-video-motion-graphics-2026',
    location: 'Mumbai',
    country: 'India',
    postedAt: '2026-08-15',
    deadline: '2026-08-25',
    budget: '₹3L – ₹8L',
    employmentType: 'Freelance',
    projectType: 'Music Video Motion Graphics',
    intentType: 'HOT',
    intentScore: 91,
    matchScore: 92,
    industry: 'Film & Media Production',
    whyThisIsAMatch: 'Active contract post seeking motion graphics artist for music video animation.',
    contactInfo: { name: 'Aman Gupta', designation: 'Creative Director', email: 'creative@beatpulse.in', phone: '+91 98200 11223' },
    description: 'BeatPulse Music is releasing an indie pop album next month. We need snappy motion graphics, lyric animations, and Instagram reel edits.',
    keywords: ['motion graphics', 'music video', 'lyric video', 'reels', 'mumbai', 'freelance'],
    status: 'DISCOVERED',
    dataStatus: 'DEMO_LOCAL',
    website: 'https://beatpulse.in',
    email: 'creative@beatpulse.in',
    phone: '+91 98200 11223',
    outreachStatus: 'DISCOVERED',
    aiScore: 91,
    scoreTier: 'HOT'
  },

  // 2. AI & Tech Startup Buyers (Bangalore / Hyderabad / Pune)
  {
    id: 'AMU-OPP-201',
    leadId: 'AMU-OPP-201',
    title: 'Need 60-Second AI Video & 3D Explainer for Product Launch',
    companyName: 'HyperScale AI Labs',
    requester: 'HyperScale AI',
    requirement: 'Looking for an AI video production partner to create a high-tech 60-second product explainer video and generative AI visuals for Series A launch.',
    matchedServices: ['AI Video Production', 'AI Image Generation', 'Corporate Videos', 'Product Videos', 'Motion Graphics'],
    serviceMatchScore: 98,
    source: 'Wellfound',
    sourceUrl: 'https://wellfound.com/l/hyperscale-ai-video-production-2026',
    location: 'Bangalore',
    country: 'India',
    postedAt: '2026-08-14',
    deadline: '2026-09-10',
    budget: '₹12L – ₹25L',
    employmentType: 'Project / Contract',
    projectType: 'AI Video & Explainer',
    intentType: 'HOT',
    intentScore: 97,
    matchScore: 98,
    industry: 'Software & AI',
    whyThisIsAMatch: 'High-value buyer request specifically seeking AI video production and product explainer video creation.',
    contactInfo: { name: 'Varun Sharma', designation: 'VP Marketing', email: 'marketing@hyperscale.ai', phone: '+91 80 4112 8800' },
    description: 'HyperScale AI is launching an enterprise agentic automation platform. We require a futuristic video combining photorealistic AI visuals and 3D product motion graphics.',
    keywords: ['ai video', 'explainer video', 'product video', 'motion graphics', 'bangalore', 'startup'],
    status: 'DISCOVERED',
    dataStatus: 'DEMO_LOCAL',
    website: 'https://hyperscale.ai',
    email: 'marketing@hyperscale.ai',
    phone: '+91 80 4112 8800',
    outreachStatus: 'DISCOVERED',
    aiScore: 97,
    scoreTier: 'HOT'
  },
  {
    id: 'AMU-OPP-202',
    leadId: 'AMU-OPP-202',
    title: 'Seeking Creative Partner for Enterprise SaaS Brand Film & Testimonial Series',
    companyName: 'CloudPulse Analytics',
    requester: 'CloudPulse SaaS',
    requirement: 'Need a video agency to shoot 4 customer case study films and a global brand manifesto video in Bangalore and Singapore.',
    matchedServices: ['Brand Films', 'Corporate Videos', 'Promotional Videos', 'Documentary/Video Editing'],
    serviceMatchScore: 94,
    source: 'LinkedIn Jobs',
    sourceUrl: 'https://www.linkedin.com/jobs/view/3902194812',
    location: 'Bangalore',
    country: 'India',
    postedAt: '2026-08-12',
    deadline: '2026-09-30',
    budget: '₹30L – ₹60L',
    employmentType: 'Project / Contract',
    projectType: 'Brand Film & Case Studies',
    intentType: 'HOT',
    intentScore: 94,
    matchScore: 94,
    industry: 'Software & AI',
    whyThisIsAMatch: 'Enterprise SaaS buyer actively seeking production agency for corporate brand films.',
    contactInfo: { name: 'Sneha Reddy', designation: 'Head of Brand Communications', email: 'sneha@cloudpulse.io', phone: '+91 80 6711 9900' },
    description: 'CloudPulse is expanding globally. We need an end-to-end video production studio to produce high-budget customer documentary films and a brand launch video.',
    keywords: ['brand film', 'corporate video', 'case study video', 'saas', 'bangalore', 'agency required'],
    status: 'DISCOVERED',
    dataStatus: 'DEMO_LOCAL',
    website: 'https://cloudpulse.io',
    email: 'sneha@cloudpulse.io',
    phone: '+91 80 6711 9900',
    outreachStatus: 'DISCOVERED',
    aiScore: 94,
    scoreTier: 'HOT'
  },

  // 3. Advertising & D2C Brand Buyers (Delhi NCR / Mumbai / Bangalore)
  {
    id: 'AMU-OPP-301',
    leadId: 'AMU-OPP-301',
    title: 'Looking for Agency for D2C Festive Ad Campaign & Instagram Reels Package',
    companyName: 'Aura Organic Skincare',
    requester: 'Aura Organics',
    requirement: 'Need an agency to shoot 10 promotional ad reels and 2 digital commercial films for our upcoming Diwali festive sale.',
    matchedServices: ['Promotional Videos', 'Reels / Shorts', 'Social Media Videos', 'AI Content Creation', 'Digital Campaigns'],
    serviceMatchScore: 96,
    source: 'Upwork',
    sourceUrl: 'https://www.upwork.com/jobs/~01a4b8c9d0e1f2g3h4',
    location: 'Delhi',
    country: 'India',
    postedAt: '2026-08-15',
    deadline: '2026-09-05',
    budget: '₹8L – ₹18L',
    employmentType: 'Project / Contract',
    projectType: 'D2C Video Campaign',
    intentType: 'HOT',
    intentScore: 95,
    matchScore: 96,
    industry: 'E-Commerce & Retail',
    whyThisIsAMatch: 'Active D2C buyer requesting agency bids for promotional ad shoot and short-form reels.',
    contactInfo: { name: 'Kavita Rastogi', designation: 'Founder & CMO', email: 'kavita@auraorganics.in', phone: '+91 11 4100 8877' },
    description: 'Aura Organics is launching a new ayurvedic skincare line. We need a creative team for studio video shoots, model casting, and short-form ad creatives.',
    keywords: ['promotional video', 'reels', 'social media video', 'd2c', 'delhi', 'agency required'],
    status: 'DISCOVERED',
    dataStatus: 'DEMO_LOCAL',
    website: 'https://auraorganics.in',
    email: 'kavita@auraorganics.in',
    phone: '+91 11 4100 8877',
    outreachStatus: 'DISCOVERED',
    aiScore: 95,
    scoreTier: 'HOT'
  },
  {
    id: 'AMU-OPP-302',
    leadId: 'AMU-OPP-302',
    title: 'Hiring Web Designer & Graphic Design Team for Rebranding Campaign',
    companyName: 'LuxeLiving Real Estate',
    requester: 'LuxeLiving Group',
    requirement: 'Seeking a digital creative studio for website redesign, key art, property brochures, and social media campaign graphics for luxury villas in Gurgaon.',
    matchedServices: ['Website Creation', 'Graphic Design', 'Posters', 'Campaign Creatives', 'Key Art'],
    serviceMatchScore: 93,
    source: 'PeoplePerHour',
    sourceUrl: 'https://www.peopleperhour.com/job/luxeliving-website-rebranding-2026',
    location: 'Delhi',
    country: 'India',
    postedAt: '2026-08-13',
    deadline: '2026-09-20',
    budget: '₹15L – ₹30L',
    employmentType: 'Project / Contract',
    projectType: 'Website & Rebranding Design',
    intentType: 'HOT',
    intentScore: 93,
    matchScore: 93,
    industry: 'Hospitality & Real Estate',
    whyThisIsAMatch: 'Luxury real estate buyer requiring web design, key art, and graphic design deliverables.',
    contactInfo: { name: 'Vikram Choudhury', designation: 'Marketing Director', email: 'vikram@luxeliving.co.in', phone: '+91 124 456 7788' },
    description: 'LuxeLiving is rebranding its Ultra-Luxury Portfolio. We need an end-to-end digital partner for custom Next.js website creation, key art, and social media creative assets.',
    keywords: ['website creation', 'graphic design', 'key art', 'real estate', 'delhi', 'gurgaon'],
    status: 'DISCOVERED',
    dataStatus: 'DEMO_LOCAL',
    website: 'https://luxeliving.co.in',
    email: 'vikram@luxeliving.co.in',
    phone: '+91 124 456 7788',
    outreachStatus: 'DISCOVERED',
    aiScore: 93,
    scoreTier: 'HOT'
  },

  // 4. Additional Buyer Opportunities (Fintech, Healthtech, Edtech, E-commerce across cities)
  {
    id: 'AMU-OPP-401',
    leadId: 'AMU-OPP-401',
    title: 'Need Motion Graphics & Explainer Video Series for Fintech App Launch',
    companyName: 'PayNext Fintech',
    requester: 'PayNext Technologies',
    requirement: 'Looking for motion graphics agency to produce 6 educational explainer videos for retail investors.',
    matchedServices: ['Motion Graphics', 'Corporate Videos', 'Motion Design', 'Social Media Videos'],
    serviceMatchScore: 94,
    source: 'LinkedIn Jobs',
    sourceUrl: 'https://www.linkedin.com/jobs/view/3910022311',
    location: 'Bangalore',
    country: 'India',
    postedAt: '2026-08-14',
    budget: '₹10L – ₹20L',
    employmentType: 'Project / Contract',
    projectType: 'Motion Graphics Series',
    intentType: 'HOT',
    intentScore: 95,
    matchScore: 94,
    industry: 'Fintech',
    whyThisIsAMatch: 'Fintech app requiring 2D motion graphics and explainer video production.',
    contactInfo: { name: 'Nikhil Merchant', designation: 'Product Lead', email: 'nikhil@paynext.in', phone: '+91 80 4900 1122' },
    description: 'PayNext is launching wealth management features. We need slick 2D motion graphics explainers.',
    keywords: ['motion graphics', 'fintech', 'explainer video', 'bangalore'],
    status: 'DISCOVERED',
    dataStatus: 'DEMO_LOCAL',
    website: 'https://paynext.in',
    email: 'nikhil@paynext.in',
    phone: '+91 80 4900 1122',
    outreachStatus: 'DISCOVERED',
    aiScore: 95,
    scoreTier: 'HOT'
  },
  {
    id: 'AMU-OPP-402',
    leadId: 'AMU-OPP-402',
    title: 'Seeking Production House for Hospital Chain Commercial Shoot',
    companyName: 'PulseCare Hospitals',
    requester: 'PulseCare Health',
    requirement: 'RFP: Looking for production company to shoot TVC and digital video campaigns across 3 hospital branches in Hyderabad and Chennai.',
    matchedServices: ['Corporate Videos', 'Promotional Videos', 'Film Production', 'Sound Design'],
    serviceMatchScore: 93,
    source: 'Company RFP',
    sourceUrl: 'https://pulsecare.in/rfp/brand-campaign-2026',
    location: 'Hyderabad',
    country: 'India',
    postedAt: '2026-08-11',
    budget: '₹20L – ₹45L',
    employmentType: 'RFP / Tender',
    projectType: 'Healthcare Commercial Shoot',
    intentType: 'HOT',
    intentScore: 94,
    matchScore: 93,
    industry: 'Healthcare & MedTech',
    whyThisIsAMatch: 'Healthcare network issuing RFP for multi-location commercial video production.',
    contactInfo: { name: 'Dr. Srinivas Rao', designation: 'COO', email: 'rfp@pulsecare.in', phone: '+91 40 2345 6789' },
    description: 'PulseCare requires a production partner for shooting patient success stories and national TVCs.',
    keywords: ['corporate video', 'tvc', 'healthcare', 'hyderabad', 'rfp'],
    status: 'DISCOVERED',
    dataStatus: 'DEMO_LOCAL',
    website: 'https://pulsecare.in',
    email: 'rfp@pulsecare.in',
    phone: '+91 40 2345 6789',
    outreachStatus: 'DISCOVERED',
    aiScore: 94,
    scoreTier: 'HOT'
  },

  // 5. Explicit Provider / Competitor Entries (Must be classified as REJECT and filtered out!)
  {
    id: 'AMU-SUPPLY-901',
    leadId: 'AMU-SUPPLY-901',
    title: 'We are a premier video production house in Mumbai',
    companyName: 'Apex Media Productions Studio',
    requester: 'Apex Media Studio',
    requirement: 'We offer turnkey video editing, motion graphics, and corporate film production services for brands.',
    matchedServices: ['Corporate Videos', 'Motion Graphics'],
    serviceMatchScore: 40,
    source: 'Public Web Directory',
    sourceUrl: 'https://apexmediastudio.com/services',
    location: 'Mumbai',
    country: 'India',
    postedAt: '2026-08-01',
    budget: 'N/A',
    employmentType: 'Full-Time',
    projectType: 'Provider Listing',
    intentType: 'REJECT',
    intentScore: 0,
    matchScore: 0,
    industry: 'Film & Media Production',
    whyThisIsAMatch: 'EXCLUDED: This is a competitor/video agency offering services (Supply), not a buyer.',
    contactInfo: { name: 'Sales Team', email: 'info@apexmediastudio.com' },
    description: 'Apex Media Studio is a full service production agency offering editing and corporate film services.',
    keywords: ['we are a video production company', 'our agency', 'video production house in mumbai'],
    status: 'REJECTED',
    website: 'https://apexmediastudio.com',
    email: 'info@apexmediastudio.com',
    phone: '+91 22 2600 0000',
    outreachStatus: 'REJECTED',
    aiScore: 0,
    scoreTier: 'COLD'
  },
  {
    id: 'AMU-SUPPLY-902',
    leadId: 'AMU-SUPPLY-902',
    title: 'Freelance Video Editor & Motion Designer Available for Hire',
    companyName: 'Rohan Sharma Freelance Portfolio',
    requester: 'Rohan Sharma',
    requirement: 'Experienced video editor available for freelance projects in Premiere Pro and After Effects. Check my portfolio.',
    matchedServices: ['Film Editing', 'Motion Graphics'],
    serviceMatchScore: 30,
    source: 'LinkedIn Profile',
    sourceUrl: 'https://linkedin.com/in/rohansharmavideoeditor',
    location: 'Bangalore',
    country: 'India',
    postedAt: '2026-08-05',
    budget: 'N/A',
    employmentType: 'Freelance',
    projectType: 'Freelancer Portfolio',
    intentType: 'REJECT',
    intentScore: 0,
    matchScore: 0,
    industry: 'Software & AI',
    whyThisIsAMatch: 'EXCLUDED: Freelancer offering editing services (Supply), not a buyer.',
    contactInfo: { name: 'Rohan Sharma', email: 'rohan.editor@gmail.com' },
    description: 'Freelance video editor looking for work.',
    keywords: ['freelance video editor available', 'my portfolio', 'hire me'],
    status: 'REJECTED',
    website: 'https://rohaneditor.com',
    email: 'rohan.editor@gmail.com',
    phone: '+91 98765 43210',
    outreachStatus: 'REJECTED',
    aiScore: 0,
    scoreTier: 'COLD'
  }
];

// Dynamically generate remaining buyer records up to 50+ diverse demand entries
const CITIES = ['Mumbai', 'Bangalore', 'Delhi', 'Hyderabad', 'Pune', 'Chennai'];
const BUYER_INDUSTRIES = [
  'E-Commerce & Retail', 'Software & AI', 'Fintech', 'Healthcare & MedTech',
  'Hospitality & Real Estate', 'Logistics & Supply Chain', 'Film & Media Production'
];
const BUYER_TYPES = ['Brand', 'Startup', 'Unicorn', 'Film Producer', 'Enterprise', 'D2C Retailer'];
const DEMAND_TEMPLATES = [
  { title: 'Seeking Agency for Product Explainer & AI Video Campaign', service: 'AI Video Production', budget: '₹10L – ₹22L', source: 'LinkedIn Jobs' },
  { title: 'Need Corporate Brand Film Production Partner', service: 'Corporate Videos', budget: '₹15L – ₹35L', source: 'Company RFP' },
  { title: 'Looking for Motion Designer for App UI Animation', service: 'Motion Graphics', budget: '₹5L – ₹12L', source: 'Contra' },
  { title: 'Need Production Designer for Ad Shoot', service: 'Production Design', budget: '₹8L – ₹15L', source: 'Upwork' },
  { title: 'Hiring Agency for Short-Form Reels & Social Content', service: 'Reels / Shorts', budget: '₹6L – ₹14L', source: 'Wellfound' },
  { title: 'Looking for Sound Designer for Web Series Post', service: 'Sound Design', budget: '₹7L – ₹16L', source: 'PeoplePerHour' },
  { title: 'Need Custom Website Creation & Key Art Design', service: 'Website Creation', budget: '₹12L – ₹28L', source: 'LinkedIn Jobs' },
  { title: 'Seeking Creative Partner for AI Image & Ad Creatives', service: 'AI Image Generation', budget: '₹4L – ₹10L', source: 'Upwork' }
];

let counter = 104;
while (BUYER_OPPORTUNITY_CATALOG.length < 52) {
  const tpl = DEMAND_TEMPLATES[counter % DEMAND_TEMPLATES.length];
  const city = CITIES[counter % CITIES.length];
  const ind = BUYER_INDUSTRIES[counter % BUYER_INDUSTRIES.length];
  const bType = BUYER_TYPES[counter % BUYER_TYPES.length];
  const idStr = `AMU-OPP-${counter}`;

  BUYER_OPPORTUNITY_CATALOG.push({
    id: idStr,
    leadId: idStr,
    title: `${tpl.title} (${city})`,
    companyName: `Apex ${bType} ${counter}`,
    requester: `Apex ${bType} ${counter}`,
    requirement: `Looking for an experienced team for ${tpl.service.toLowerCase()} and creative campaign deliverables in ${city}.`,
    matchedServices: [tpl.service, 'Social Media Content', 'Motion Graphics'],
    serviceMatchScore: 90 + (counter % 8),
    source: tpl.source,
    sourceUrl: `https://www.example-jobs.com/listing/${idStr.toLowerCase()}`,
    location: city,
    country: 'India',
    postedAt: `2026-08-${15 - (counter % 10)}`,
    deadline: `2026-09-${10 + (counter % 15)}`,
    budget: tpl.budget,
    employmentType: counter % 2 === 0 ? 'Project / Contract' : 'Freelance',
    projectType: `${tpl.service} Opportunity`,
    intentType: counter % 5 === 0 ? 'WARM' : 'HOT',
    intentScore: 88 + (counter % 10),
    matchScore: 90 + (counter % 8),
    industry: ind,
    whyThisIsAMatch: `Genuine buyer requirement seeking ${tpl.service} in ${city}.`,
    contactInfo: { name: `Manager ${counter}`, designation: 'Marketing Lead', email: `buyer${counter}@apexbrand.in`, phone: `+91 98000 ${counter}00` },
    description: `Active buyer project requirement for ${tpl.service} in ${city}. High priority response requested.`,
    keywords: [tpl.service.toLowerCase(), city.toLowerCase(), ind.toLowerCase(), 'looking for', 'need a'],
    status: 'DISCOVERED',
    dataStatus: 'DEMO_LOCAL',
    website: `https://apexbrand${counter}.in`,
    email: `buyer${counter}@apexbrand.in`,
    phone: `+91 98000 ${counter}00`,
    outreachStatus: 'DISCOVERED',
    aiScore: 88 + (counter % 10),
    scoreTier: 'HOT'
  });
  counter++;
}

module.exports = { BUYER_OPPORTUNITY_CATALOG };
